# Generated by Django 5.0.2 on 2024-02-15 17:05

from django.db import migrations
from . import create_default_user


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_create_user_model"),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
