# Generated by Django 5.0.2 on 2024-02-25 12:44

import json

from django.conf import settings
from django.db import migrations


def create_codes(apps, schema_editor):
    codes_app = "codes"
    Code = apps.get_model(codes_app, "Code")

    categories_app = "categories"
    Category = apps.get_model(categories_app, "Category")

    with open(settings.FIXTURES[codes_app], "r") as f:
        codes = json.load(f)

    for category, category_codes in codes.items():
        category = Category.objects.get(description = category)
        Code.objects.bulk_create([
            Code(description = code, category = category) for code in category_codes
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0001_create_code_model"),
    ]

    operations = [
        migrations.RunPython(create_codes)
    ]