version: "3"
   
services:
  db:
    image: postgres
    ports: 
      - '5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=icd
      - POSTGRES_USER=icd
      - POSTGRES_PASSWORD=icd
    networks:
      - djangonetwork
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=icd
      - POSTGRES_USER=icd
      - POSTGRES_PASSWORD=icd
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge