version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    image: death_cause_tagger_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so when we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
  
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/backend/celery/worker/Dockerfile
    image: death_cause_tagger_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/backend/celery/beat/Dockerfile
    image: death_cause_tagger_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/backend/celery/flower/Dockerfile
    image: death_cause_tagger_celery_flower
    command: /start-celeryflower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: