import os


SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'superuser')


class Status:
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    REJECTED = 'REJECTED'
    PENDING_REVIEW = 'PENDING REVIEW'