# Generated by Django 5.1.2 on 2024-10-18 08:06

import json

from django.conf import settings
from django.db import migrations


def create_mappings(apps, schema_editor):
    codes_app = "codes"
    Code = apps.get_model(codes_app, "Code")

    death_causes_app = "deathcauses"
    DeathCause = apps.get_model(death_causes_app, "DeathCause")

    mappings_app = "mappings"
    Mapping = apps.get_model(mappings_app, "Mapping")

    with open(settings.FIXTURES[mappings_app], "r") as f:
        data = json.load(f)
    
    codes, death_causes = data["code"], data["death_cause"]
    is_option, is_active, is_open = data["is_option"], data["is_active"], data["is_open"]

    mappings = []

    for c, d, opt, act, ope in zip(codes, death_causes, is_option, is_active, is_open):
        mappings.append(
            Mapping(
                code = Code.objects.get(description = c),
                death_cause = DeathCause.objects.get(description = d),
                is_option = opt,
                is_active = act,
                is_open = ope
            )
        )

    Mapping.objects.bulk_create(mappings)


class Migration(migrations.Migration):

    dependencies = [
        ("mappings", "0001_create_mapping_model"),
    ]

    operations = [
        migrations.RunPython(create_mappings)
    ]