# Generated by Django 5.0.2 on 2024-02-20 17:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "approved"),
                            (1, "rejected"),
                            (2, "pending"),
                        ],
                        default=2,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "status_updated_on",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        editable=False,
                        monitor="status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=users.models.User.get_default_user,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status_updated_by",
                    models.ForeignKey(
                        default=users.models.User.get_default_user,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updated_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=users.models.User.get_default_user,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
    ]
