# Generated by Django 5.0.2 on 2024-02-20 17:26

import json

from django.conf import settings
from django.db import migrations


def create_categories(apps, schema_editor):
    app = "categories"
    Category = apps.get_model(app, "Category")

    with open(settings.FIXTURES[app], "r") as f:
        descriptions = json.load(f)

    Category.objects.bulk_create([
        Category(description = desc) for desc in descriptions 
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_create_category_model"),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
