version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/app/Dockerfile
    image: backend
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so when we change code on the host, code in the docker container will also be changed
    volumes:
      - ../src:/src
    ports:
      - 8010:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=imd2021
      - DJANGO_SUPERUSER_EMAIL=admin@email.com
      - DEBUG=1
      - SECRET_KEY=django-insecure-&as$$33x!ya%k=0niu567jkm=k^zb)t60c6iywzrqmut@#twtop
    depends_on:
      - redis
      - db
  
  db:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./backend/celery/worker/Dockerfile
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - ../src:/src
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./backend/celery/beat/Dockerfile
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - ../src:/src
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery_flower:
    build:
      context: .
      dockerfile: ./backend/celery/flower/Dockerfile
    image: celery_flower
    command: /start-celeryflower
    volumes:
      - ../src:/src
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres: