# Generated by Django 5.0.2 on 2024-02-25 14:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("codes", "0002_create_codes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_active_updated_on",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        editable=False,
                        monitor="is_active",
                        verbose_name="active updated on",
                    ),
                ),
                ("threshold", models.PositiveSmallIntegerField()),
                (
                    "code_above",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="above",
                        to="codes.code",
                    ),
                ),
                (
                    "code_below",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="below",
                        to="codes.code",
                    ),
                ),
                (
                    "code_equal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equal",
                        to="codes.code",
                    ),
                ),
                (
                    "code_input",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period",
                        to="codes.code",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=users.models.User.get_default_user,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_active_updated_by",
                    models.ForeignKey(
                        default=users.models.User.get_default_user,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_active_updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="active updated by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=users.models.User.get_default_user,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Periods",},
        ),
    ]
