# Generated by Django 5.0.2 on 2024-02-25 14:33

import json

from django.conf import settings
from django.db import migrations


def create_periods(apps, schema_editor):
    codes_app = "codes"
    Code = apps.get_model(codes_app, "Code")

    periods_app = "periods"
    Period = apps.get_model(periods_app, "Period")

    with open(settings.FIXTURES[periods_app], "r") as f:
        periods = json.load(f)

    periods = [
        Period(
            code_input = Code.objects.get(description = record["code_input"]),
            threshold = record["threshold"],
            code_below = Code.objects.get(description = record["code_below"]),
            code_equal = Code.objects.get(description = record["code_equal"]),
            code_above = Code.objects.get(description = record["code_above"]),
        ) for record in periods       
    ]
    Period.objects.bulk_create(periods)


class Migration(migrations.Migration):

    dependencies = [
        ("periods", "0001_create_period_model"),
    ]

    operations = [
        migrations.RunPython(create_periods)
    ]