# Generated by Django 3.2.9 on 2022-12-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER category_search_vector_trigger
            BEFORE INSERT OR UPDATE OF description, search_vector
            ON tagger_category
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', description
            );
            UPDATE tagger_category SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS category_search_vector_trigger
            ON tagger_category;
            """
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER mapping_search_vector_trigger
            BEFORE INSERT OR UPDATE OF description, search_vector
            ON tagger_mapping
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', description
            );
            UPDATE tagger_mapping SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS mapping_search_vector_trigger
            ON tagger_mapping;
            """
        )
    ]
