# Generated by Django 3.2.9 on 2022-12-17 15:58

import os
from django.db import migrations
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(
        username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'superuser'),
        password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'password'), 
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_search_vector_trigger'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code = migrations.RunPython.noop),
    ]
