# Generated by Django 3.2.9 on 2022-12-06 16:23

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_mapping_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tagger_mapp_search__3cf9c6_gin'),
        ),
    ]
