# Generated by Django 3.2.9 on 2022-12-06 20:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0005_search_vector_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='tagger_mapping_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
