# Generated by Django 3.2.9 on 2022-12-09 16:07

import json
from django.db import migrations
from django.conf import settings


def create_new_categories(apps, schema_editor):
    NewCategory = apps.get_model('tagger', 'NewCategory')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    with open('tagger/fixtures/categories.json', 'r') as f:
        descriptions = json.load(f)

    user = User.objects.get(username = 'admin')
    new_categories = [
        NewCategory(description = desc, created_by = user, modified_by = user) for desc in descriptions
    ]

    NewCategory.objects.bulk_create(new_categories)


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0008_auto_20221209_2314'),
    ]

    operations = [
        migrations.RunPython(create_new_categories, reverse_code = migrations.RunPython.noop),
    ]
