# Generated by Django 3.2.9 on 2022-12-09 17:56

import json
from django.db import migrations
from django.conf import settings


def create_new_codes(apps, schema_editor):
    NewCode = apps.get_model('tagger', 'NewCode')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    with open('tagger/fixtures/codes.json', 'r') as f:
        codes = json.load(f)

    user = User.objects.get(username = 'admin')
    new_codes= [
        NewCode(**code, created_by = user, modified_by = user) for code in codes
    ]

    NewCode.objects.bulk_create(new_codes)


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0010_newcode'),
    ]

    operations = [
        migrations.RunPython(create_new_codes, reverse_code = migrations.RunPython.noop),
    ]
