# Generated by Django 3.2.9 on 2022-12-09 18:24

import json
from django.db import migrations
from django.conf import settings


def create_new_periods(apps, schema_editor):
    NewPeriod = apps.get_model('tagger', 'NewPeriod')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    with open('tagger/fixtures/periods.json', 'r') as f:
        periods = json.load(f)

    user = User.objects.get(username = 'admin')
    new_periods= [
        NewPeriod(**period, created_by = user, modified_by = user) for period in periods
    ]

    NewPeriod.objects.bulk_create(new_periods)


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0012_newperiod'),
    ]

    operations = [
        migrations.RunPython(create_new_periods, reverse_code = migrations.RunPython.noop),
    ]