# Generated by Django 3.2.9 on 2022-12-13 17:21

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagger', '0013_auto_20221210_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('is_option', models.BooleanField(default=False)),
                ('optioned_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_mappings', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='tagger.newcode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mappings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_mappings', to=settings.AUTH_USER_MODEL)),
                ('optioned_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optioned_mappings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='newmapping',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tagger_newm_search__baad5d_gin'),
        ),
        migrations.AddIndex(
            model_name='newmapping',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='tagger_newmapping_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
