# Generated by Django 3.2.9 on 2022-12-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0014_auto_20221214_0121'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER mapping_search_vector_trigger
            BEFORE INSERT OR UPDATE OF description, search_vector
            ON tagger_newmapping
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', description
            );
            UPDATE tagger_newmapping SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS mapping_search_vector_trigger
            ON tagger_newmapping;
            """
        )
    ]