# Generated by Django 3.2.9 on 2022-12-13 15:47

import json
from django.db import migrations
from django.conf import settings
from django.utils import timezone


def create_new_mappings(apps, schema_editor):
    NewMapping = apps.get_model('tagger', 'NewMapping')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    with open('tagger/fixtures/mappings.json', 'r') as f:
        mappings = json.load(f)

    user = User.objects.get(username = 'admin')

    new_mappings = []
    now = timezone.now()
    for mapping in mappings:
        mapping.update({'is_option': bool(mapping['is_option'])})
        if mapping['is_option']:
            new_mappings.append(
                NewMapping(**mapping, optioned_by = user, optioned_on = now, is_approved = True, approved_by = user, approved_on = now, created_by = user, modified_by = user)
            )
        else:
            new_mappings.append(
                NewMapping(**mapping, is_approved = True, approved_by = user, approved_on = now, created_by = user, modified_by = user)
            )
    NewMapping.objects.bulk_create(new_mappings)

 
class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0015_auto_20221213_2344'),
    ]

    operations = [
        migrations.RunPython(create_new_mappings, reverse_code = migrations.RunPython.noop),
    ]