# Generated by Django 5.0.2 on 2024-02-15 17:05

import os

from django.db import migrations


def create_default_user(apps, schema_editor):
    """
    Create default user if it does not exist.
    """
    User = apps.get_model("users.User")

    username = os.getenv("DEFAULT_USER", "admin")
    password = os.getenv("DEFAULT_PASSWORD", "admin")

    try:
        User.objects.get(username = username)
        
    except User.DoesNotExist:
        User.objects.create_superuser(username, password)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_create_user_model"),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
