name: Pytest

on:
    push:
        branches:
            - ninja
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        
        steps:
            -   name: Checkout repository code
                uses: actions/checkout@v4

            -   name: Set up Python 3.10
                uses: actions/setup-python@v4
                with:
                    python-version: "3.10"

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r backend/requirements.txt
                    pip install coverage==7.4.3 pytest==8.0.2 pytest-cov==4.1.0 pytest-django==4.8.0

            -   name: Run unit tests and code coverage
                run: |
                    pytest --cov
                env:
                    POSTGRES_HOST: postgres